### ISSUE TITLE
Upgrade to repose 8

### ISSUE THREAD

**Issue by mburns** [mmi-cookbooks/ele-repose#57]
# Description

We need to upgrade `8.0.1.0` to stay current on Repose's support window.

# TODO
- [x] custom bundle upgrade https://github.com/rackerlabs/cloud-monitoring-filter-bundle/pull/10
- [x] upgrade `node['repose']['version']`

# How to Test
- [ ] run smoke tests
